
const
  HAVE_IEEEFP* = 1
  HOST_FILLORDER* = Fillorder_Lsb2msb
  HOST_BIGENDIAN* = 0
  CCITT_SUPPORT* = 1
  LOGLUV_SUPPORT* = 1
  LZW_SUPPORT* = 1
  NEXT_SUPPORT* = 1
  PACKBITS_SUPPORT* = 1
  PIXARLOG_SUPPORT* = 1
  THUNDER_SUPPORT* = 1
  ZIP_SUPPORT* = 1
  STRIPCHOP_DEFAULT* = 1
  SUBIFD_SUPPORT* = 1
  DEFAULT_EXTRASAMPLE_AS_ALPHA* = 1
  CHECK_JPEG_YCBCR_SUBSAMPLING* = 1
  MDI_SUPPORT* = 1
  COLORIMETRY_SUPPORT* = true
  YCBCR_SUPPORT* = true
  CMYK_SUPPORT* = true
  ICC_SUPPORT* = true
  PHOTOSHOP_SUPPORT* = true
  IPTC_SUPPORT* = true
